### ISSUE TITLE
pyinstaller error on windows

### ISSUE THREAD

**Issue by gearcapitan** [micle-fm/Parat#1]
PS C:\Users\gearc\Documents> pyinstaller .\backdoor.pyw -noconsole
237 INFO: PyInstaller: 3.4.dev0+5f9190544
238 INFO: Python: 2.7.14
239 INFO: Platform: Windows-10-10.0.16299
240 INFO: wrote C:\Users\gearc\Documents\oconsole.spec
241 INFO: UPX is not available.
243 INFO: Extending PYTHONPATH with paths
['C:\\Users\\gearc\\Documents', 'C:\\Users\\gearc\\Documents']
243 INFO: checking Analysis
244 INFO: Building Analysis because out00-Analysis.toc is non existent
244 INFO: Initializing module dependency graph...
248 INFO: Initializing module graph hooks...
297 INFO: running Analysis out00-Analysis.toc
307 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
405 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da3
8fdebd0e6822.manifest
406 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_a
cd0e4ffe1daef0a.manifest
408 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_a
cce041fe1dd7bc9.manifest
500 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9317_none ...
500 INFO: Found manifest C:\Windows\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e
0939fa840d57b.manifest
515 INFO: Searching for file msvcr90.dll
516 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\
msvcr90.dll
516 INFO: Searching for file msvcp90.dll
516 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\
msvcp90.dll
516 INFO: Searching for file msvcm90.dll
517 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\
msvcm90.dll
603 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da3
8fdebd0e6822.manifest
604 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_a
cd0e4ffe1daef0a.manifest
604 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_a
cce041fe1dd7bc9.manifest
605 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
703 INFO: Caching module hooks...
708 INFO: Analyzing C:\Users\gearc\Documents\backdoor.pyw
1994 INFO: Processing pre-safe import module hook   _xmlplus
2880 INFO: Processing pre-find module path hook   distutils
3073 INFO: Loading module hooks...
3073 INFO: Loading module hook "hook-distutils.py"...
3076 INFO: Loading module hook "hook-xml.py"...
3146 INFO: Loading module hook "hook-httplib.py"...
3149 INFO: Loading module hook "hook-encodings.py"...
3741 INFO: Loading module hook "hook-sqlite3.py"...
3819 INFO: Looking for ctypes DLLs
3867 INFO: Analyzing run-time hooks ...
3872 INFO: Looking for dynamic libraries
4079 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_
a551ff35e6a96bed.manifest
4168 INFO: Searching for assembly amd64_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.4148_none ...
4169 INFO: Found manifest C:\Windows\WinSxS\Manifests\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_04
480933ab2137b1.manifest
4172 INFO: Searching for file mfc90.dll
4173 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_04480933ab2137b1
\mfc90.dll
4173 INFO: Searching for file mfc90u.dll
4174 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_04480933ab2137b1
\mfc90u.dll
4175 INFO: Searching for file mfcm90.dll
4175 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_04480933ab2137b1
\mfcm90.dll
4176 INFO: Searching for file mfcm90u.dll
4176 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_04480933ab2137b1
\mfcm90u.dll
4262 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_
a551ff35e6a96bed.manifest
4263 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 4148)
4448 INFO: Looking for eggs
4448 INFO: Using Python library C:\Windows\system32\python27.dll
4449 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9,
 0, 30729, 4148), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch
=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9317), publicKeyToken=u'1fc8b3b9a1e18e3b')]
4451 INFO: Warnings written to C:\Users\gearc\Documents\build\oconsole\warnoconsole.txt
4476 INFO: Graph cross-reference written to C:\Users\gearc\Documents\build\oconsole\xref-oconsole.html
4523 INFO: checking PYZ
4523 INFO: Building PYZ because out00-PYZ.toc is non existent
4523 INFO: Building PYZ (ZlibArchive) C:\Users\gearc\Documents\build\oconsole\out00-PYZ.pyz
4825 INFO: Building PYZ (ZlibArchive) C:\Users\gearc\Documents\build\oconsole\out00-PYZ.pyz completed successfully.
4857 INFO: checking PKG
4858 INFO: Building PKG because out00-PKG.toc is non existent
4858 INFO: Building PKG (CArchive) out00-PKG.pkg
4900 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
4903 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
4904 INFO: checking EXE
4905 INFO: Building EXE because out00-EXE.toc is non existent
4906 INFO: Building EXE from out00-EXE.toc
4907 INFO: Appending archive to EXE C:\Users\gearc\Documents\build\oconsole\oconsole.exe
4910 INFO: Building EXE from out00-EXE.toc completed successfully.
4915 INFO: checking COLLECT
4917 INFO: Building COLLECT because out00-COLLECT.toc is non existent
4921 INFO: Building COLLECT out00-COLLECT.toc
4927 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+5f9190544', 'console_scripts', 'pyinstaller')()
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "c:\python27\lib\site-packages\PyInstaller\building\api.py", line 661, in __init__
    self.__postinit__()
  File "c:\python27\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\python27\lib\site-packages\PyInstaller\building\api.py", line 691, in assemble
    dist_nm=inm)
  File "c:\python27\lib\site-packages\PyInstaller\building\utils.py", line 202, in checkCache
    os.remove(cachedfile)
WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado: u'C:\\Users\\gearc\\AppData\\Roaming\\p
yinstaller\\bincache00_py27_64bit\\msvcp90.dll'

![captura de pantalla 306](https://user-images.githubusercontent.com/13740942/36300439-ec8cd804-12c6-11e8-8733-720d8a5e0cc7.png)

**Comment by micle-fm** [comment]
Make sure that your PyInstaller is latest version and you have using **correct form**:

![pyinstaller_test](https://serving.photos.photobox.com/377341572108589b1a4561aa4636e667f70c644de2963c0a546fc7da85a07897e09c601f.jpg)

In this picture you see pyinstaller worked without any error by running bellow command on *python 2*:
`python -m PyInstaller --onefile --noconsole PATH_TO_SERVER.PYW`

**Comment by gearcapitan** [comment]
WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado: u'C:\\Users\\gearc\\AppData\\Roaming\\p
yinstaller\\bincache00_py27_64bit\\msvcp90.dll'

**Comment by federicoemartinez** [comment]
@gearcapitan 

I think you need the Microsoft Visual C++ 2008 Redistributable:

https://www.microsoft.com/en-us/download/details.aspx?id=29
