### ISSUE TITLE
how you start listener ?

### ISSUE THREAD

**Issue by mateo24xx** [micle-fm/Parat#2]
sorry can understand exactly how this tool work??
for eample when you say to write " listen  -p "
can you tell please what is the right phrase or syntax to write to start listener ? 
just write the full command that i have to write to start listener
thanks

**Comment by micle-fm** [comment]
When you start main, it read port from config file located on `conf/config.ini` and **listen** on that. For see which port(s) is/are listening you can use `listen --show` and for listen on new port(s), use `listen -p YOUR_PORT` syntax.
All information for usages are accessable with `-h` or `--help` options(e.g. `command -h`)

Good luck!
